//http://minifiedjs.com/builder/
// minified.js config start -- use this comment to re-create configuration in the Builder
// - Only sections animate, dollardollar, each, fadeslide, get, 
// - ie9compatibility, loop, ready, request, set, text.

(function(){function s(a){return"string"==typeof a}function u(a){return a&&a.nodeType}function q(a){return a&&null!=a.length&&!s(a)&&!u(a)&&!k(a)}function p(a,b){for(var c in a)a.hasOwnProperty(c)&&b(c,a[c]);return a}function g(a,b){for(var c=0;a&&c<a.length;c++)b(a[c],c);return a}function J(a,b){var c=[],d=k(b)?b:function(a){return b!=a};g(a,function(a,b){d(a,b)&&c.push(a)});return c}function y(a,b){var c=[];g(a,function(a,e){q(a=b(a,e))?g(a,function(a){c.push(a)}):null!=a&&c.push(a)});return c}
function K(a,b){var c=[];p(a,function(a,e){q(a=b(a,e))?g(a,function(a){c.push(a)}):null!=a&&c.push(a)});return c}function m(a,b,c){return(null!=a?""+a:"").replace(b,c||"")}function k(a){return"function"==typeof a&&!a.item}function z(a,b){A.setTimeout(a,b||0)}function r(a){return parseFloat(m(a,/^[^\d-]+/))}function L(a,b){function c(a){u(a)&&!e[n=a.minified=a.minified||++M]&&(d.push(a),e[n]=!0)}var d=[],e={},n;g(a,function(a){a=b(a);q(a)?g(a,c):c(a)});return d}function F(a){var b={$position:"absolute",
$visibility:"hidden",$display:"block",$height:null},c=a.get(b);a.set(b);b=a.get("$height",!0);a.set(c);return b}function G(a){a()}function H(a){B?B.push(a):z(a)}function t(a,b,c){return k(a)?H(a):new D(C(a,b,c))}function C(a,b,c){function d(a){a=function h(a){return q(a)?y(a,h):a}(a);return e?J(a,function(a){for(;a=a.parentNode;){if(a===e)return!0;if(c)return!1}}):a}var e;if(b&&1!=(b=C(b)).length)return L(b,function(b){return C(a,b,c)});e=b&&b[0];if(!s(a))return d(q(a)?a:[a]);b=(e||I).querySelectorAll(a);
return e?d(b):b}function E(){function a(a,e){null==b&&(b=a,c=e,z(function(){g(d,G)}))}var b,c=[],d=[],e=a.then=function(a,e){function h(){try{var d=b?a:e;if(k(d)){var h=d.apply(null,c);h&&k(h.then)?h.then(function(a){f(!0,[a])},function(a){f(!1,[a])}):f(!0,[h])}else f(b,c)}catch(g){f(!1,[g])}}var f=E();null!=b?z(h):d.push(h);return f};a.error=function(a){return e(0,a)};return a}function D(a){for(var b=this.length=a.length,c=0;c<b;c++)this[c]=a[c]}var A=this,I=document,M=1,B=[],x=[],O=A.requestAnimationFrame||
function(a){z(a,33)};p({each:function(a){return g(this,a)},text:function(){function a(b){var c=u(b);return 1==c?y(b.childNodes,a):5>c?b.data:null}return y(this,a).join("")},get:function(a,b){var c=this,d=c[0];if(d){if(s(a)){var e=m(m(a,/^%/,"data-"),/^[$@]/),n;n="$"==a?d.className:"$$"==a?d.getAttribute("style"):!/\$\$/.test(a)||"hidden"!=d.style.visibility&&"none"!=d.style.display?"$$fade"==a?isNaN(n=r(d.style.opacity))?1:n:"$$slide"==a?c.get("$height"):/^\$/.test(a)?A.getComputedStyle(d,null).getPropertyValue(m(e,
/[A-Z]/g,function(a){return"-"+a.toLowerCase()})):/^[@%]/.test(a)?d.getAttribute(e):d[e]:0;return b?r(n):n}var l={};(q(a)?g:p)(a,function(a){l[a]=c.get(a,b)});return l}},set:function(a,b){function c(a,b,c){null!=c?a.setAttribute(b,c):a.removeAttribute(b)}var d=this,e;void 0!==b?"$$fade"==a||"$$slide"==a?d.set({$visibility:0<(e=r(b))?"visible":"hidden",$display:"block"}).set("$$fade"==a?{$opacity:e}:{$height:/px/.test(b)?b:function(a,b,c){return e*(e&&F(t(c)))+"px"},$overflow:"hidden"}):g(d,function(d,
e){var h=m(m(a,/^%/,"data-"),/^[@$]/),f=d.className||"",v=/^\$/.test(a)?d.style:d,w=k(b)?b(t(d).get(a),e,d):b;"$"==a?null!=w&&(g(w.split(/\s+/),function(a){var b=m(a,/^[+-]/),c=f;f=m(f,RegExp("\\b"+b+"\\b","i"));if(/^\+/.test(a)||b==a&&c==f)f+=" "+b}),d.className=m(f,/^\s+|\s+(?=\s|$)/g)):"$$"==a?c(d,"style",w):/^[@%]/.test(a)?c(v,h,w):v[h]=w}):s(a)||k(a)?d.set("$",a):p(a,function(a,b){d.set(a,b)});return d},animate:function(a,b,c,d){var e=this,n=[],l=/-?[\d.]+/,h,f=E(),v=k(c)?c:function(a,b,d){return a+
d*(b-a)*(c+(1-c)*d*(3-2*d))};d=d||{};d.time=0;d.stop=function(){h();f(!1)};b=b||500;c=c||0;g(e,function(b){var c={a:t(b),c:{}};p(c.b=c.a.get(a),function(b,d){var e=a[b];"$$slide"==b&&(e=e*F(c.a)+"px");c.c[b]=/^[+-]=/.test(e)?m(e.substr(2),l,r(d)+r(m(e,/\+?=/))):e});n.push(c)});h=t.loop(function(a){function c(a,b){return/^#/.test(a)?parseInt(6<a.length?a.substr(1+2*b,2):(a=a.charAt(1+b))+a,16):parseInt(m(a,/[^\d,]+/g).split(",")[b])}d.time=a;a>=b||0>a?(g(n,function(a){a.a.set(a.c)}),h(),d.time=null,
f(!0,[e])):g(n,function(d){p(d.b,function(e,h){var f="rgb(",g=d.c[e],n=a/b;if(/^#|rgb\(/.test(g))for(var k=0;3>k;k++)f+=Math.round(v(c(h,k),c(g,k),n))+(2>k?",":")");else f=v(r(h),r(g),n),f=m(g,l,null!=f?""+f:"");d.a.set(e,f)})})});return f},e:null},function(a,b){D.prototype[a]=b});p({request:function(a,b,c,d,e,g){var l,h=c,f=0,k=E();try{l=new XMLHttpRequest,null!=c&&(d=d||{},s(c)||u(c)||(h=K(c,function N(a,b){return q(b)?y(b,function(b){return N(a,b)}):encodeURIComponent(a)+(null!=b?"="+encodeURIComponent(b):
"")}).join("&")),/post/i.test(a)?u(c)||(s(c)||d["Content-Type"])||(d["Content-Type"]="application/x-www-form-urlencoded"):(b+="?"+h,h=null)),l.open(a,b,!0,e,g),p(d,function(a,b){l.setRequestHeader(a,b)}),l.onreadystatechange=function(){4!=l.readyState||f++||(200==l.status?k(!0,[l.responseText,l.responseXML]):k(!1,[l.status,l.statusText,l.responseText]))},l.send(h)}catch(m){f||k(!1,[0,null,null!=m?""+m:""])}return k},ready:H,loop:function(a){var b={d:a,f:(new Date).getTime(),b:function(){for(var a=
0;a<x.length;a++)x[a]===b&&x.splice(a--,1)}};2>x.push(b)&&function d(){g(x,function(a){a.d(Math.max(0,(new Date).getTime()-a.f),a.b)}).length&&O(d)}();return b.b},e:null},function(a,b){t[a]=b});I.addEventListener("DOMContentLoaded",function(){g(B,G);B=null},!1);var P={$:t,$$:function(a){return C(a)[0]},M:D};A.require=function(a){if("minified"==a)return P}})();
