# This compose file adds stubby4j https://hub.docker.com/r/azagniotov/stubby4j to your stack
#
# See "Environment variables" section at https://hub.docker.com/r/azagniotov/stubby4j
version: '3.5'
services:
  stubby4j-jre8:
    # 'root' - so that stubby4j can write 'logs' into host machine's directory mapped to container volume
    user: root
    image: azagniotov/stubby4j:latest-jre8
    # '/home/circleci/project/docker/smoke-test/yaml' - local path on Circle CI 'machine' type executor
    volumes:
      - "/home/circleci/project/docker/smoke-test/yaml:/home/stubby4j/data"
    container_name: stubby4j_jre8
    ports:
      - 8884:8884
      - 8891:8891
      - 7445:7445
    environment:
      YAML_CONFIG: smoke-tests-stubs.yaml
      STUBS_PORT: 8884
      ADMIN_PORT: 8891
      STUBS_TLS_PORT: 7445
      WITH_DEBUG: --debug
      WITH_WATCH: --watch
