# Configuration for CircleCI
circle_working_directory: &circle_working_directory
  working_directory: ~/repo


base_environment: &base_environment
  <<: *circle_working_directory
  environment:
    # Customize the JVM maximum heap limit
    JVM_OPTS: -Xmx3200m
    TERM: dumb

gradle_7_2_0_jdk8_environment: &gradle_7_2_0_jdk8_environment
  <<: *base_environment
  docker:
    - image: gradle:7.2.0-jdk8-openj9@sha256:d4128edf5ac579f93e3149a9f89be3af779de1d3d85a9f25f25cb3d4b432b69a

filter_ignore_gh_pages: &filter_ignore_gh_pages
  filters:
    branches:
      ignore:
        - gh-pages

default_steps: &default_steps
  steps:
    - run: echo "Skipping.."

jobs:
  no_op_job:
    <<: *gradle_7_2_0_jdk8_environment
    <<: *default_steps

version: 2.1
workflows:

  master-jdk8:
    jobs:
      - no_op_job:
          <<: *filter_ignore_gh_pages
