# Java Gradle CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details
#
defaults: &defaults
  working_directory: ~/repo
  environment:
    # Customize the JVM maximum heap limit
    JVM_OPTS: -Xmx3200m
    TERM: dumb

  # https://discuss.circleci.com/t/show-test-results-for-prospective-merge-of-a-github-pr/1662/14
  # https://support.circleci.com/hc/en-us/articles/360047521451-Why-is-CIRCLE-PR-NUMBER-empty-
  steps:
    - checkout
    - run:
        name: Building a PR branch merge
        command: git pull --ff-only origin "refs/pull/${CIRCLE_PULL_REQUEST##*/}/merge"
    - run: git branch
    - run: git log -n 2
    - run: java -version
    - run: ./gradlew --version

    # Download and cache dependencies
    - restore_cache:
        keys:
          - v1-dependencies-{{ checksum "build.gradle" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

    - save_cache:
        paths:
          - ~/.gradle
        key: v1-dependencies-{{ checksum "build.gradle" }}

    - run:
        name: Run all test suits
        command: ./gradlew clean test integrationTest functionalTest
        when: always

    - run:
        name: Run JaCoCo plugin code coverage
        when: on_success
        command: |
          if [ "$CIRCLE_JOB" = "gradle_6_8_3_jdk8_openj9" ]; then
              ./gradlew clean jacocoTestReport
          else
              echo "Skipping 'Run JaCoCo plugin code coverage' on job '$CIRCLE_JOB' as per config.yml"
          fi

    - run:
        name: Upload code coverage data to Codecov
        when: on_success
        command: |
          if [ "$CIRCLE_JOB" = "gradle_6_8_3_jdk8_openj9" ]; then
              bash <(curl -s https://codecov.io/bash)
          else
              echo "Skipping 'Upload code coverage data to Codecov' on job '$CIRCLE_JOB' as per config.yml"
          fi


jobs:
  gradle_6_8_3_jdk8_openj9:
    docker:
      - image: gradle:6.8.3-jdk8-openj9@sha256:9a6af40de81c839063ebd767523ad3bf3b0a4d449101a7c1e354b3233a97eeaa
    <<: *defaults

  gradle_6_8_3_jdk11_openj9:
    docker:
      - image: gradle:6.8.3-jdk11-openj9@sha256:3608d73c73897f0919c942012a299eb66be9c113fba3324c0bbcb0fae69f548e
    <<: *defaults

  gradle_6_8_3_jdk15:
    docker:
      - image: gradle:6.8.3-jdk15@sha256:642395fe8f800d292d01073ecdb8ffd0d4995305b5856fda6a8cf52514877183
    <<: *defaults

version: 2.1
workflows:

  build-test-code-coverage:
    jobs:
      - gradle_6_8_3_jdk8_openj9
      - gradle_6_8_3_jdk11_openj9
      - gradle_6_8_3_jdk15

  nightly:
    triggers:
      - schedule:
          cron: "15 19 * * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - gradle_6_8_3_jdk8_openj9
      - gradle_6_8_3_jdk11_openj9
      - gradle_6_8_3_jdk15
