# Java Gradle CircleCI 2.1 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details
#
defaults: &defaults
  working_directory: ~/repo
  environment:
    # Customize the JVM maximum heap limit
    JVM_OPTS: -Xmx3200m
    TERM: dumb

  steps:
    - checkout
    - run: java -version

    # Download and cache dependencies
    - restore_cache:
        keys:
          - v1-dependencies-{{ checksum "build.gradle" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

    - save_cache:
        paths:
          - ~/.gradle
        key: v1-dependencies-{{ checksum "build.gradle" }}

    - run:
        name: Run all test suits
        command: ./gradlew clean test integrationTest functionalTest
        when: always

    - run:
        name: Run JaCoCo plugin code coverage
        when: on_success
        command: |
          if [ "$CIRCLE_JOB" = "gradle_6_7_1_jdk8_openj9" ]; then
              ./gradlew clean jacocoTestReport
          else
              echo "Skipping 'Run JaCoCo plugin code coverage' on job '$CIRCLE_JOB' as per config.yml"
          fi

    - run:
        name: Upload code coverage data to Codecov
        when: on_success
        command: |
          if [ "$CIRCLE_JOB" = "gradle_6_7_1_jdk8_openj9" ]; then
              bash <(curl -s https://codecov.io/bash)
          else
              echo "Skipping 'Upload code coverage data to Codecov' on job '$CIRCLE_JOB' as per config.yml"
          fi

jobs:
  gradle_6_7_1_jdk8_openj9:
    docker:
      - image: gradle:6.7.1-jdk8-openj9@sha256:917922c2dcddf66493b4ad55b576b5fde4cb77344ecab250c7c3e710f03137eb
    <<: *defaults

  gradle_6_7_1_jdk11_openj9:
    docker:
      - image: gradle:6.7.1-jdk11-openj9@sha256:0ea7abec757ae57b1e5298732e3141c528563029c76a8637faf854222fa36fe0
    <<: *defaults

  gradle_6_7_1_jdk15:
    docker:
      - image: gradle:6.7.1-jdk15@sha256:b1366cd238eb775bcea6ed1d15908a326dfefa99061e16a6a156042661bba99a
    <<: *defaults

workflows:
  version: 2
  build-test-code-coverage:
    jobs:
      - gradle_6_7_1_jdk8_openj9
      - gradle_6_7_1_jdk11_openj9
      - gradle_6_7_1_jdk15
