# Java Gradle CircleCI 2.1 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details
#

#############################################################################################
## Anchors definition
#############################################################################################
circle_working_directory: &circle_working_directory
  working_directory: ~/repo


base_environment: &base_environment
  <<: *circle_working_directory
  environment:
    # Customize the JVM maximum heap limit
    JVM_OPTS: -Xmx3200m
    TERM: dumb


gradle_6_8_3_jdk8_environment: &gradle_6_8_3_jdk8_environment
  <<: *base_environment
  docker:
    - image: gradle:6.8.3-jdk8-openj9@sha256:9a6af40de81c839063ebd767523ad3bf3b0a4d449101a7c1e354b3233a97eeaa


gradle_6_8_3_jdk11_environment: &gradle_6_8_3_jdk11_environment
  <<: *base_environment
  docker:
    - image: gradle:6.8.3-jdk11-openj9@sha256:3608d73c73897f0919c942012a299eb66be9c113fba3324c0bbcb0fae69f548e


gradle_6_8_3_jdk15_environment: &gradle_6_8_3_jdk15_environment
  <<: *base_environment
  docker:
    - image: gradle:6.8.3-jdk15@sha256:642395fe8f800d292d01073ecdb8ffd0d4995305b5856fda6a8cf52514877183


context_docker_hub: &context_docker_hub
  context:
    - Docker-Hub-Credentials


filter_only_master: &filter_only_master
  filters:
    branches:
      only:
        - master

filter_ignore_master: &filter_ignore_master
  filters:
    branches:
      ignore:
        - master

twelve_hour_master_trigger: &twelve_hour_master_trigger
  triggers:
    - schedule:
        cron: "15 7,19 * * *"
        <<: *filter_only_master


condition_when_not_master: &condition_when_not_master
  condition:
    not:
      equal: [ master, << pipeline.git.branch >> ]


pr_to_master_merge_branch_steps: &pr_to_master_merge_branch_steps
  steps:
    - run:
        name: Creating pr-to-master merge branch to run the tests on
        command: git pull --ff-only origin "refs/pull/${CIRCLE_PULL_REQUEST##*/}/merge"
    - run:
        name: "Sanity check: listing current git branch name"
        command: git branch
    - run:
        name: "Sanity check: listing git merge commit"
        command: git log -n 2


default_steps: &default_steps
  # https://discuss.circleci.com/t/show-test-results-for-prospective-merge-of-a-github-pr/1662/14
  # https://support.circleci.com/hc/en-us/articles/360047521451-Why-is-CIRCLE-PR-NUMBER-empty-
  steps:
    - checkout
    - when:
        <<: *condition_when_not_master
        # https://support.circleci.com/hc/en-us/articles/360006357533--CIRCLE-PULL-REQUEST-is-missing-from-my-Pull-Request
        <<: *pr_to_master_merge_branch_steps

    - run: java -version

    - run: ./gradlew --version

    # Download and cache dependencies
    - restore_cache:
        keys:
          - v1-dependencies-{{ checksum "build.gradle" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

    - save_cache:
        paths:
          - ~/.gradle
        key: v1-dependencies-{{ checksum "build.gradle" }}

    - run:
        name: Run all test suits
        command: ./gradlew clean test integrationTest functionalTest
        when: always


code_coverage_steps: &code_coverage_steps
  # https://discuss.circleci.com/t/show-test-results-for-prospective-merge-of-a-github-pr/1662/14
  # https://support.circleci.com/hc/en-us/articles/360047521451-Why-is-CIRCLE-PR-NUMBER-empty-
  steps:
    - checkout
    - when:
        <<: *condition_when_not_master
        # https://support.circleci.com/hc/en-us/articles/360006357533--CIRCLE-PULL-REQUEST-is-missing-from-my-Pull-Request
        <<: *pr_to_master_merge_branch_steps

    - run: java -version

    - run: ./gradlew --version

    # Download and cache dependencies
    - restore_cache:
        keys:
          - v1-dependencies-{{ checksum "build.gradle" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

    - save_cache:
        paths:
          - ~/.gradle
        key: v1-dependencies-{{ checksum "build.gradle" }}

    - run:
        name: Run JaCoCo plugin code coverage
        when: on_success
        command: ./gradlew clean jacocoTestReport

    - run:
        name: Upload code coverage data to Codecov
        when: on_success
        command: bash <(curl -s https://codecov.io/bash)



build_push_image_steps: &build_push_image_steps
  steps:
    - checkout

    - run:
        name: Authenticating to Docker Hub
        command: |
          echo "$DOCKER_HUB_PASSWORD" | docker login --username $DOCKER_HUB_USER --password-stdin

    # build the application image
    - run:
        name: Building Docker image
        working_directory: ~/repo/docker/jdk<< parameters.jdk_version >>
        command: docker build --rm --no-cache -t azagniotov/stubby4j:latest-jre<< parameters.jdk_version >> .

    # deploy the image
    - run:
        name: Pushing Docker image to Docker Hub
        working_directory: ~/repo/docker/jdk<< parameters.jdk_version >>
        command: docker push azagniotov/stubby4j


#############################################################################################
## Jobs definition
#############################################################################################
jobs:

  gradle_6_8_3_jdk8:
    <<: *gradle_6_8_3_jdk8_environment
    <<: *default_steps


  gradle_6_8_3_jdk8_code_coverage:
    <<: *gradle_6_8_3_jdk8_environment
    <<: *code_coverage_steps


  gradle_6_8_3_jdk11:
    <<: *gradle_6_8_3_jdk11_environment
    <<: *default_steps


  gradle_6_8_3_jdk15:
    <<: *gradle_6_8_3_jdk15_environment
    <<: *default_steps


  docker_build_latest_jre8:
    parameters:
      jdk_version:
        type: string
        default: "8"

    machine: true
    <<: *circle_working_directory
    <<: *build_push_image_steps


  docker_build_latest_jre11:
    parameters:
      jdk_version:
        type: string
        default: "11"

    machine: true
    <<: *circle_working_directory
    <<: *build_push_image_steps


  docker_build_latest_jre15:
    parameters:
      jdk_version:
        type: string
        default: "15"

    machine: true
    <<: *circle_working_directory
    <<: *build_push_image_steps


#############################################################################################
## Workflows definition
#############################################################################################

version: 2.1
workflows:

  master-jdk8:
    jobs:
      - gradle_6_8_3_jdk8


  branch-jdk8:
    jobs:
      - gradle_6_8_3_jdk8:
          <<: *filter_ignore_master
      - gradle_6_8_3_jdk8_code_coverage:
          <<: *filter_ignore_master
          requires:
            - gradle_6_8_3_jdk8


  branch-jdk11:
    jobs:
      - gradle_6_8_3_jdk11:
          <<: *filter_ignore_master


  branch-jdk15:
    jobs:
      - gradle_6_8_3_jdk15:
          <<: *filter_ignore_master


  master-twelve-hour-jdk8:
    <<: *twelve_hour_master_trigger
    jobs:
      - gradle_6_8_3_jdk8
      - docker_build_latest_jre8:
          <<: *context_docker_hub
          requires:
            - gradle_6_8_3_jdk8


  master-twelve-hour-jdk11:
    <<: *twelve_hour_master_trigger
    jobs:
      - gradle_6_8_3_jdk11
      - docker_build_latest_jre11:
          <<: *context_docker_hub
          requires:
            - gradle_6_8_3_jdk11


  master-twelve-hour-jdk15:
    <<: *twelve_hour_master_trigger
    jobs:
      - gradle_6_8_3_jdk15
      - docker_build_latest_jre15:
          <<: *context_docker_hub
          requires:
            - gradle_6_8_3_jdk15
