# Java Gradle CircleCI 2.1 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details
#

#############################################################################################
## Anchors definition
#############################################################################################
circle_working_directory: &circle_working_directory
  working_directory: ~/repo


base_environment: &base_environment
  <<: *circle_working_directory
  environment:
    # Customize the JVM maximum heap limit
    JVM_OPTS: -Xmx3200m

    # For JDK 8 for the specific JDK vendor used by stubby4j on CircleCI
    OPENJ9_JAVA_OPTIONS: -DoverrideDisabledAlgorithms=true

    # As of JDK 9 (incl.) respected by all JDK vendors
    JDK_JAVA_OPTIONS: -DoverrideDisabledAlgorithms=true

    TERM: dumb


context_docker_hub: &context_docker_hub
  context:
    - Docker-Hub-Credentials


context_sonatype: &context_sonatype
  context:
    - Sonatype-Credentials


docker_in_docker_environment: &docker_in_docker_environment
  <<: *base_environment
  docker:
    - image: docker:20.10.8-alpine3.14@sha256:6ac2f3862aa1353a5fe6bf12439f3e56e695e56d7c3098898c96ef33eae78bf9

###########################################################################################
### START: Different JDK images
###########################################################################################
openjdk_alpine_jdk_8u111_environment: &openjdk_alpine_jdk_8u111_environment
  <<: *base_environment
  docker:
    - image: openjdk:8u111-jdk-alpine@sha256:d49bf8c44670834d3dade17f8b84d709e7db47f1887f671a0e098bafa9bae49f

azul_zulu_openjdk_alpine_jdk_8u282_environment: &azul_zulu_openjdk_alpine_jdk_8u282_environment
  <<: *base_environment
  docker:
    - image: azul/zulu-openjdk-alpine:8u282-8.52.0.23@sha256:2b5f8470ce568c0630e5caaf1ad9be47c8d51ef950c79d33b5853df4ec1cdcd3

adoptopenjdk_openjdk_alpine_jdk_8u312_b07_environment: &adoptopenjdk_openjdk_alpine_jdk_8u312_b07_environment
  <<: *base_environment
  docker:
    - image: adoptopenjdk/openjdk8:jdk8u312-b07-alpine-slim@sha256:da6bb7b3d1bc1a23653c60f88902be9ca15b4a62f537970d37b65dd374be3221

azul_zulu_openjdk_alpine_jdk_11_48_environment: &azul_zulu_openjdk_alpine_jdk_11_48_environment
  <<: *base_environment
  docker:
    - image: azul/zulu-openjdk-alpine:11.0.11-11.48.21@sha256:c860f15777f40676bb3fb4eb3c2f362d0b32a40260b9d06c4d645a633efe5739
###########################################################################################
### END: Different JDK images
###########################################################################################


gradle_7_2_0_jdk8_environment: &gradle_7_2_0_jdk8_environment
  <<: *base_environment
  docker:
    - image: gradle:7.2.0-jdk8-openj9@sha256:d4128edf5ac579f93e3149a9f89be3af779de1d3d85a9f25f25cb3d4b432b69a


gradle_7_2_0_jdk11_environment: &gradle_7_2_0_jdk11_environment
  <<: *base_environment
  docker:
    - image: gradle:7.2.0-jdk11-openj9@sha256:6c628ab1edc7b733b4880804fcd27dc360fc350f333546924e64e3a34a009fa2


gradle_7_2_0_jdk16_environment: &gradle_7_2_0_jdk16_environment
  <<: *base_environment
  docker:
    - image: gradle:7.2.0-jdk16-openj9@sha256:9620865af4f35026abfc9680603449296f832ea79da9a7f4e79d00989ccddcee


filter_only_master: &filter_only_master
  filters:
    branches:
      only:
        - master

filter_ignore_master: &filter_ignore_master
  filters:
    branches:
      ignore:
        - master

#twelve_hour_master_trigger: &twelve_hour_master_trigger
#  triggers:
#    - schedule:
#        cron: "15 7,19 * * *"
#        <<: *filter_only_master

condition_when_not_master: &condition_when_not_master
  condition:
    not:
      equal: [ master, << pipeline.git.branch >> ]


condition_when_master: &condition_when_master
  condition:
      equal: [ master, << pipeline.git.branch >> ]


pr_to_master_merge_branch_steps: &pr_to_master_merge_branch_steps
  steps:
    - run:
        name: Creating pr-to-master merge branch to run the tests on
        command: git pull --ff-only origin "refs/pull/${CIRCLE_PULL_REQUEST##*/}/merge"
    - run:
        name: "Sanity check: listing current git branch name"
        command: git branch
    - run:
        name: "Sanity check: listing git merge commit"
        command: git log -n 2


publish_snapshot_steps: &publish_snapshot_steps
  steps:
    - run:
        name: Configure Gradle to Sonatype authentication
        command: |
          echo "sonatypeUsername=$sonatypeUsername" > /home/gradle/.gradle/gradle.properties
          echo "sonatypePassword=$sonatypePassword" >> /home/gradle/.gradle/gradle.properties

    - run:
        name: Building artifacts
        command: gradle -PciRun clean build
        when: on_success

    - run:
        name: Publish SNAPSHOT artifacts to OSS Sonatype snapshots repository
        command: |
          echo "::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::"
          echo -e ":::     ATTENTION:\tThe SNAPSHOT artifacts are not signed by GPG"
          echo "::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::"
          gradle publish
        when: on_success


default_steps: &default_steps
  # https://discuss.circleci.com/t/show-test-results-for-prospective-merge-of-a-github-pr/1662/14
  # https://support.circleci.com/hc/en-us/articles/360047521451-Why-is-CIRCLE-PR-NUMBER-empty-
  steps:
    - checkout
    - when:
        <<: *condition_when_not_master
        # https://support.circleci.com/hc/en-us/articles/360006357533--CIRCLE-PULL-REQUEST-is-missing-from-my-Pull-Request
        <<: *pr_to_master_merge_branch_steps

    - run: java -version

    - run: gradle --version

    # Download and cache dependencies
    - restore_cache:
        keys:
          - v2-dependencies-{{ checksum "conf/gradle/dependencies.gradle" }}
          # fallback to using the latest cache if no exact match is found
          - v2-dependencies-

    - save_cache:
        paths:
          - ~/.gradle
        key: v2-dependencies-{{ checksum "conf/gradle/dependencies.gradle" }}

    - run:
        name: Run all test suits
        command: gradle -PciRun clean test integrationTest functionalTest
        when: always

    - when:
        <<: *condition_when_master
        <<: *publish_snapshot_steps


code_coverage_steps: &code_coverage_steps
  # https://discuss.circleci.com/t/show-test-results-for-prospective-merge-of-a-github-pr/1662/14
  # https://support.circleci.com/hc/en-us/articles/360047521451-Why-is-CIRCLE-PR-NUMBER-empty-
  steps:
    - checkout
    - when:
        <<: *condition_when_not_master
        # https://support.circleci.com/hc/en-us/articles/360006357533--CIRCLE-PULL-REQUEST-is-missing-from-my-Pull-Request
        <<: *pr_to_master_merge_branch_steps

    - run: java -version

    - run: gradle --version

    # Download and cache dependencies
    - restore_cache:
        keys:
          - v2-dependencies-{{ checksum "conf/gradle/dependencies.gradle" }}
          # fallback to using the latest cache if no exact match is found
          - v2-dependencies-

    - save_cache:
        paths:
          - ~/.gradle
        key: v2-dependencies-{{ checksum "conf/gradle/dependencies.gradle" }}

    - run:
        name: Run JaCoCo plugin code coverage
        when: on_success
        command: gradle -PciRun clean jacocoTestReport

    - run:
        name: Upload code coverage data to Codecov
        when: on_success
        command: echo "Skipping CodeCov Skipping CodeCov Bash Uploader"



build_push_image_steps: &build_push_image_steps
  steps:
    - checkout

    - setup_remote_docker:
        version: 20.10.7

    # build the application image
    - run:
        name: Building Docker image
        working_directory: ~/repo/docker/jdk<< parameters.jdk_version >>
        command: docker build --rm --no-cache -t azagniotov/stubby4j:latest-jre<< parameters.jdk_version >> .

    - run:
        name: Authenticating to Docker Hub
        command: |
          echo "$DOCKER_HUB_PASSWORD" | docker login --username "$DOCKER_HUB_USER" --password-stdin

    # deploy the image
    - run:
        name: Pushing Docker image to Docker Hub
        working_directory: ~/repo/docker/jdk<< parameters.jdk_version >>
        command: docker push azagniotov/stubby4j:latest-jre<< parameters.jdk_version >>


smoke_test_steps: &smoke_test_steps
  steps:
    - checkout
    - run:
        name: Install cURL on Alpine Linux
        command: |
          apk --no-cache add curl && curl --version

    - run:
        name: Build stubby4j uber JAR
        command: ./gradlew -PciRun clean build

    - run:
        when: on_success
        name: Make requests to the stubby4j over TLSv1, TLSv1.1 & TLSv1.2
        command: |
          java -jar build/libs/stubby4j-*.jar \
            --location 127.0.0.1 \
            --tls 7445 \
            --data smoke-test/yaml/smoke-tests-stubs.yaml &

          echo "stubby4j started!"
          sleep 5

          sh smoke-test/shell/make_request_using_curl.sh 1.0 127.0.0.1 7445
          sh smoke-test/shell/make_request_using_curl.sh 1.1 127.0.0.1 7445
          sh smoke-test/shell/make_request_using_curl.sh 1.2 127.0.0.1 7445


#############################################################################################
## Jobs definition
#############################################################################################
jobs:

  smoke_openjdk_openjdk_8u111:
    <<: *openjdk_alpine_jdk_8u111_environment
    <<: *smoke_test_steps


  smoke_azul_zulu_openjdk_8u282:
    <<: *azul_zulu_openjdk_alpine_jdk_8u282_environment
    <<: *smoke_test_steps


  smoke_adoptopenjdk_openjdk_8u312_b07:
    <<: *adoptopenjdk_openjdk_alpine_jdk_8u312_b07_environment
    <<: *smoke_test_steps


  smoke_azul_zulu_openjdk_11_48:
    <<: *azul_zulu_openjdk_alpine_jdk_11_48_environment
    <<: *smoke_test_steps


  gradle_7_2_0_jdk8:
    <<: *gradle_7_2_0_jdk8_environment
    <<: *default_steps


  gradle_7_2_0_jdk8_code_coverage:
    <<: *gradle_7_2_0_jdk8_environment
    <<: *code_coverage_steps


  gradle_7_2_0_jdk11:
    <<: *gradle_7_2_0_jdk11_environment
    <<: *default_steps


  gradle_7_2_0_jdk16:
    <<: *gradle_7_2_0_jdk16_environment
    <<: *default_steps


  docker_build_latest_jre8:
    parameters:
      jdk_version:
        type: string
        default: "8"
    <<: *docker_in_docker_environment
    <<: *build_push_image_steps


  docker_build_latest_jre11:
    parameters:
      jdk_version:
        type: string
        default: "11"
    <<: *docker_in_docker_environment
    <<: *build_push_image_steps


  docker_build_latest_jre16:
    parameters:
      jdk_version:
        type: string
        default: "16"
    <<: *docker_in_docker_environment
    <<: *build_push_image_steps


#############################################################################################
## Workflows definition
#############################################################################################

version: 2.1
workflows:

  master-jdk8:
    jobs:
      - gradle_7_2_0_jdk8:
          <<: *context_sonatype
          <<: *filter_only_master


  branch-smoke-test:
    jobs:
      - smoke_openjdk_openjdk_8u111:
          <<: *filter_ignore_master
      - smoke_azul_zulu_openjdk_8u282:
          <<: *filter_ignore_master
      - smoke_adoptopenjdk_openjdk_8u312_b07:
          <<: *filter_ignore_master
      - smoke_azul_zulu_openjdk_11_48:
          <<: *filter_ignore_master

  master-smoke-test:
    jobs:
      - smoke_openjdk_openjdk_8u111:
          <<: *filter_only_master
      - smoke_azul_zulu_openjdk_8u282:
          <<: *filter_only_master
      - smoke_adoptopenjdk_openjdk_8u312_b07:
          <<: *filter_only_master
      - smoke_azul_zulu_openjdk_11_48:
          <<: *filter_only_master

  branch-jdk8:
    jobs:
      - gradle_7_2_0_jdk8:
          <<: *filter_ignore_master
      - gradle_7_2_0_jdk8_code_coverage:
          <<: *filter_ignore_master
          requires:
            - gradle_7_2_0_jdk8


  branch-jdk11:
    jobs:
      - gradle_7_2_0_jdk11:
          <<: *filter_ignore_master


  branch-jdk16:
    jobs:
      - gradle_7_2_0_jdk16:
          <<: *filter_ignore_master


  master-twelve-hour-smoke-test:
    triggers:
      - schedule:
          cron: "5 7,19 * * *"
          <<: *filter_only_master
    jobs:
      - smoke_openjdk_openjdk_8u111
      - smoke_azul_zulu_openjdk_8u282
      - smoke_adoptopenjdk_openjdk_8u312_b07


  master-twelve-hour-jdk8:
    triggers:
      - schedule:
          cron: "10 7,19 * * *"
          <<: *filter_only_master
    jobs:
      - gradle_7_2_0_jdk8:
          <<: *context_sonatype
      - docker_build_latest_jre8:
          <<: *context_docker_hub
          requires:
            - gradle_7_2_0_jdk8


  master-twelve-hour-jdk11:
    triggers:
      - schedule:
          cron: "15 7,19 * * *"
          <<: *filter_only_master
    jobs:
      - gradle_7_2_0_jdk11:
          <<: *context_sonatype
      - docker_build_latest_jre11:
          <<: *context_docker_hub
          requires:
            - gradle_7_2_0_jdk11


  master-twelve-hour-jdk16:
    triggers:
      - schedule:
          cron: "20 7,19 * * *"
          <<: *filter_only_master
    jobs:
      - gradle_7_2_0_jdk16:
          <<: *context_sonatype
      - docker_build_latest_jre16:
          <<: *context_docker_hub
          requires:
            - gradle_7_2_0_jdk16
