# Java Gradle CircleCI 2.1 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details
#

#############################################################################################
## Anchors definition
#############################################################################################
circle_working_directory: &circle_working_directory
  working_directory: ~/repo


base_environment: &base_environment
  <<: *circle_working_directory
  environment:
    # Customize the JVM maximum heap limit
    JVM_OPTS: -Xmx3200m
    TERM: dumb


context_docker_hub: &context_docker_hub
  context:
    - Docker-Hub-Credentials


context_sonatype: &context_sonatype
  context:
    - Sonatype-Credentials


docker_in_docker_environment: &docker_in_docker_environment
  <<: *base_environment
  docker:
    - image: docker:20.10.8-alpine3.14@sha256:6ac2f3862aa1353a5fe6bf12439f3e56e695e56d7c3098898c96ef33eae78bf9


gradle_7_0_2_jdk8_environment: &gradle_7_0_2_jdk8_environment
  <<: *base_environment
  docker:
    - image: gradle:7.0.2-jdk8-openj9@sha256:9065a4a1d9004c9b32c5586c0dfdef960c10767c470533f11f2c6e3985af51b2


gradle_7_0_2_jdk11_environment: &gradle_7_0_2_jdk11_environment
  <<: *base_environment
  docker:
    - image: gradle:7.0.2-jdk11-openj9@sha256:7fe39a8ae7a2e4282a4f57248b18268efc96c858709820d2dcff1c2a5cf2c0e7


gradle_7_0_2_jdk16_environment: &gradle_7_0_2_jdk16_environment
  <<: *base_environment
  docker:
    - image: gradle:7.0.2-jdk16-openj9@sha256:e53668d3b02639a554a24991658a7dbbb380652fe8f530c09ee7e69991ecc69e


filter_only_master: &filter_only_master
  filters:
    branches:
      only:
        - master

filter_ignore_master: &filter_ignore_master
  filters:
    branches:
      ignore:
        - master

#twelve_hour_master_trigger: &twelve_hour_master_trigger
#  triggers:
#    - schedule:
#        cron: "15 7,19 * * *"
#        <<: *filter_only_master

condition_when_not_master: &condition_when_not_master
  condition:
    not:
      equal: [ master, << pipeline.git.branch >> ]


condition_when_master: &condition_when_master
  condition:
      equal: [ master, << pipeline.git.branch >> ]


pr_to_master_merge_branch_steps: &pr_to_master_merge_branch_steps
  steps:
    - run:
        name: Creating pr-to-master merge branch to run the tests on
        command: git pull --ff-only origin "refs/pull/${CIRCLE_PULL_REQUEST##*/}/merge"
    - run:
        name: "Sanity check: listing current git branch name"
        command: git branch
    - run:
        name: "Sanity check: listing git merge commit"
        command: git log -n 2


publish_snapshot_steps: &publish_snapshot_steps
  steps:
    - run:
        name: Publish SNAPSHOT version to OSS Sonatype snapshots repository
        command: gradle -PciRun clean build publish
        when: on_success


default_steps: &default_steps
  # https://discuss.circleci.com/t/show-test-results-for-prospective-merge-of-a-github-pr/1662/14
  # https://support.circleci.com/hc/en-us/articles/360047521451-Why-is-CIRCLE-PR-NUMBER-empty-
  steps:
    - checkout
    - when:
        <<: *condition_when_not_master
        # https://support.circleci.com/hc/en-us/articles/360006357533--CIRCLE-PULL-REQUEST-is-missing-from-my-Pull-Request
        <<: *pr_to_master_merge_branch_steps

    - run: java -version

    - run: gradle --version

    # Download and cache dependencies
    - restore_cache:
        keys:
          - v2-dependencies-{{ checksum "conf/gradle/dependencies.gradle" }}
          # fallback to using the latest cache if no exact match is found
          - v2-dependencies-

    - save_cache:
        paths:
          - ~/.gradle
        key: v2-dependencies-{{ checksum "conf/gradle/dependencies.gradle" }}

    - run:
        name: Run all test suits
        command: gradle -PciRun clean test integrationTest functionalTest
        when: always

    - when:
        <<: *condition_when_master
        <<: *publish_snapshot_steps


code_coverage_steps: &code_coverage_steps
  # https://discuss.circleci.com/t/show-test-results-for-prospective-merge-of-a-github-pr/1662/14
  # https://support.circleci.com/hc/en-us/articles/360047521451-Why-is-CIRCLE-PR-NUMBER-empty-
  steps:
    - checkout
    - when:
        <<: *condition_when_not_master
        # https://support.circleci.com/hc/en-us/articles/360006357533--CIRCLE-PULL-REQUEST-is-missing-from-my-Pull-Request
        <<: *pr_to_master_merge_branch_steps

    - run: java -version

    - run: gradle --version

    # Download and cache dependencies
    - restore_cache:
        keys:
          - v1-dependencies-{{ checksum "build.gradle" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

    - save_cache:
        paths:
          - ~/.gradle
        key: v1-dependencies-{{ checksum "build.gradle" }}

    - run:
        name: Run JaCoCo plugin code coverage
        when: on_success
        command: gradle clean jacocoTestReport

    - run:
        name: Upload code coverage data to Codecov
        when: on_success
        command: echo "Skipping CodeCov Skipping CodeCov Bash Uploader"



build_push_image_steps: &build_push_image_steps
  steps:
    - checkout

    - setup_remote_docker:
        version: 20.10.7

    # build the application image
    - run:
        name: Building Docker image
        working_directory: ~/repo/docker/jdk<< parameters.jdk_version >>
        command: docker build --rm --no-cache -t azagniotov/stubby4j:latest-jre<< parameters.jdk_version >> .

    - run:
        name: Authenticating to Docker Hub
        command: |
          echo "$DOCKER_HUB_PASSWORD" | docker login --username "$DOCKER_HUB_USER" --password-stdin

    # deploy the image
    - run:
        name: Pushing Docker image to Docker Hub
        working_directory: ~/repo/docker/jdk<< parameters.jdk_version >>
        command: docker push azagniotov/stubby4j:latest-jre<< parameters.jdk_version >>


smoke_test_in_docker_compose_steps: &smoke_test_in_docker_compose_steps
  steps:
    - checkout
    - run:
        name: Start stubby4j container
        # The `docker-compose up` command aggregates the output of each container. When
        # the command exits, all containers are stopped. Running `docker-compose up -d`
        # starts the containers in the background and leaves them running.
        command: |
          cd /home/circleci/project/docker/smoke-test && docker-compose up -d

    - run:
        # ubuntu-2004:202107-02 uses 'ash' shell, not 'bash'
        name: Make cURL request to the stubby4j container
        command: |
          sleep 1
          smoke_test_response=$(docker run \
            --network container:stubby4j_service appropriate/curl \
            --retry 10 --retry-delay 1 --retry-connrefused --silent  \
            -X GET -H "Content-Type: application/json" \
            http://localhost:8882/tests/smoke-test/1)

          if [ "$smoke_test_response" != "OK" ]
          then
            echo "Got response $smoke_test_response from stubby4j container, failing ... "
            exit 1
          else
            echo "Smoke tests passed!"
            exit 0
          fi

#############################################################################################
## Jobs definition
#############################################################################################
jobs:

  smoke_test_in_docker:
    # When using docker-compose with volumes (i.e.: sharing of local directories with a container),
    # a 'machine' executor type is required: https://circleci.com/docs/2.0/executor-types/#docker-benefits-and-limitations
    machine:
      # https://circleci.com/docs/2.0/configuration-reference/#available-machine-images
      image: ubuntu-2004:202107-02
    <<: *smoke_test_in_docker_compose_steps

  gradle_7_0_2_jdk8:
    <<: *gradle_7_0_2_jdk8_environment
    <<: *default_steps


  gradle_7_0_2_jdk8_code_coverage:
    <<: *gradle_7_0_2_jdk8_environment
    <<: *code_coverage_steps


  gradle_7_0_2_jdk11:
    <<: *gradle_7_0_2_jdk11_environment
    <<: *default_steps


  gradle_7_0_2_jdk16:
    <<: *gradle_7_0_2_jdk16_environment
    <<: *default_steps


  docker_build_latest_jre8:
    parameters:
      jdk_version:
        type: string
        default: "8"
    <<: *docker_in_docker_environment
    <<: *build_push_image_steps


  docker_build_latest_jre11:
    parameters:
      jdk_version:
        type: string
        default: "11"
    <<: *docker_in_docker_environment
    <<: *build_push_image_steps


  docker_build_latest_jre15:
    parameters:
      jdk_version:
        type: string
        default: "15"
    <<: *docker_in_docker_environment
    <<: *build_push_image_steps


#############################################################################################
## Workflows definition
#############################################################################################

version: 2.1
workflows:

  master-jdk8:
    jobs:
      - gradle_7_0_2_jdk8:
          <<: *context_sonatype
          <<: *filter_only_master


  smoke-test:
    jobs:
      - smoke_test_in_docker:
          <<: *filter_only_master


  branch-jdk8:
    jobs:
      - gradle_7_0_2_jdk8:
          <<: *filter_ignore_master
      - gradle_7_0_2_jdk8_code_coverage:
          <<: *filter_ignore_master
          requires:
            - gradle_7_0_2_jdk8


  branch-jdk11:
    jobs:
      - gradle_7_0_2_jdk11:
          <<: *filter_ignore_master


  branch-jdk15:
    jobs:
      - gradle_7_0_2_jdk16:
          <<: *filter_ignore_master


  master-twelve-hour-smoke-test:
    triggers:
      - schedule:
          cron: "5 7,19 * * *"
          <<: *filter_only_master
    jobs:
      - smoke_test_in_docker


  master-twelve-hour-jdk8:
    triggers:
      - schedule:
          cron: "10 7,19 * * *"
          <<: *filter_only_master
    jobs:
      - gradle_7_0_2_jdk8:
          <<: *context_sonatype
      - docker_build_latest_jre8:
          <<: *context_docker_hub
          requires:
            - gradle_7_0_2_jdk8


  master-twelve-hour-jdk11:
    triggers:
      - schedule:
          cron: "15 7,19 * * *"
          <<: *filter_only_master
    jobs:
      - gradle_7_0_2_jdk11:
          <<: *context_sonatype
      - docker_build_latest_jre11:
          <<: *context_docker_hub
          requires:
            - gradle_7_0_2_jdk11


  master-twelve-hour-jdk16:
    triggers:
      - schedule:
          cron: "20 7,19 * * *"
          <<: *filter_only_master
    jobs:
      - gradle_7_0_2_jdk16:
          <<: *context_sonatype
      - docker_build_latest_jre15:
          <<: *context_docker_hub
          requires:
            - gradle_7_0_2_jdk16
