- proxy-config:
    description: this is a catch-all proxy config
    strategy: as-is
    properties:
      endpoint: https://jsonplaceholder.typicode.com

- proxy-config:
    uuid: some-unique-name
    strategy: custom
    properties:
      endpoint: https://jsonplaceholder.typicode.com

- proxy-config:
    description: description-2
    uuid: some-unique-name-two
    strategy: custom
    properties:
      endpoint: https://google.com

- proxy-config:
    description: description-3
    uuid: some-unique-name-three
    strategy: custom
    properties:
      endpoint: https://google.com
