- proxy-config:
    description: this is a catch-all proxy config
    strategy: as-is
    properties:
      endpoint: https://jsonplaceholder.typicode.com

- proxy-config:
    uuid: some-unique-name
    strategy: custom
    properties:
      endpoint: https://jsonplaceholder.typicode.com
