- proxy-config:
    description: this is a default catch-all config
    strategy: as-is
    properties:
      endpoint: https://jsonplaceholder.typicode.com

- proxy-config:
    description: woah! this is a unique proxy-config
    uuid: some-unique-name
    strategy: custom
    properties:
      endpoint: https://jsonplaceholder.typicode.com
