- proxy-config:
    proxy-name: DEFAULT
    proxy-strategy: as-is
    proxy-properties:
      endpoint: https://jsonplaceholder.typicode.com

- proxy-config:
    proxy-name: some-unique-name
    proxy-strategy: as-is
    proxy-properties:
      endpoint: https://jsonplaceholder.typicode.com