- proxy-config:
    strategy: as-is
    properties:
      endpoint: https://jsonplaceholder.typicode.com

- proxy-config:
    uuid: some-unique-name
    strategy: additive
    properties:
      endpoint: https://jsonplaceholder.typicode.com

- request:
    method:
      - GET
      - POST
      - PUT
    url: ^/resources/asn/.*$

  response:
    status: 200
    body: >
      {"status": "ASN found!"}
    headers:
      content-type: application/json
