- proxy-config:
    uuid: some-unique-name
    strategy: as-is
    properties:
      endpoint: https://jsonplaceholder.typicode.com

- proxy-config:
    uuid: another-unique-name
    strategy: additive
    properties:
      endpoint: https://jsonplaceholder.typicode.com
