- web-socket:
    description: this is a web-socket config
    url: /items/furniture
    sub-protocols: echo, mamba, zumba

    on-open:
      policy: once
      message-type: text
      body: You have been successfully connected
      delay: 2000

